[2025-05-15T19:40:09.323+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-15T19:40:09.344+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_manga_database.update_manga_db manual__2025-05-15T19:39:40.818082+00:00 [queued]>
[2025-05-15T19:40:09.353+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_manga_database.update_manga_db manual__2025-05-15T19:39:40.818082+00:00 [queued]>
[2025-05-15T19:40:09.355+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-05-15T19:40:09.370+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): update_manga_db> on 2025-05-15 19:39:40.818082+00:00
[2025-05-15T19:40:09.377+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1436) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-15T19:40:09.379+0000] {standard_task_runner.py:72} INFO - Started process 1441 to run task
[2025-05-15T19:40:09.381+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'update_manga_database', 'update_manga_db', 'manual__2025-05-15T19:39:40.818082+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/update_manga_database_dag.py', '--cfg-path', '/tmp/tmpamw3ryvw']
[2025-05-15T19:40:09.382+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask update_manga_db
[2025-05-15T19:40:09.427+0000] {task_command.py:467} INFO - Running <TaskInstance: update_manga_database.update_manga_db manual__2025-05-15T19:39:40.818082+00:00 [running]> on host 3729034b4972
[2025-05-15T19:40:09.513+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_manga_database' AIRFLOW_CTX_TASK_ID='update_manga_db' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T19:39:40.818082+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-15T19:39:40.818082+00:00'
[2025-05-15T19:40:09.515+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-15T19:40:09.516+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-15T19:40:09.516+0000] {logging_mixin.py:190} INFO - Current task name:update_manga_db state:running start_date:2025-05-15 19:40:09.345358+00:00
[2025-05-15T19:40:09.517+0000] {logging_mixin.py:190} INFO - Dag name:update_manga_database and current dag run status:running
[2025-05-15T19:40:09.517+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-15T19:40:09.519+0000] {log.py:232} WARNING - 2025-05-15 19:40:09,518 - INFO: Starting manga data update
[2025-05-15T19:40:09.518+0000] {update_manga_database_dag.py:373} INFO - Starting manga data update
[2025-05-15T19:40:09.529+0000] {log.py:232} WARNING - 2025-05-15 19:40:09,529 - INFO: Transaction started
[2025-05-15T19:40:09.529+0000] {update_manga_database_dag.py:84} INFO - Transaction started
[2025-05-15T19:40:09.532+0000] {log.py:232} WARNING - 2025-05-15 19:40:09,532 - INFO: Checking 5 manga for updates
[2025-05-15T19:40:09.532+0000] {update_sequential.py:59} INFO - Checking 5 manga for updates
[2025-05-15T19:40:13.902+0000] {log.py:232} WARNING - 2025-05-15 19:40:13,901 - INFO: Database update complete
[2025-05-15T19:40:13.901+0000] {update_sequential.py:119} INFO - Database update complete
[2025-05-15T19:40:13.906+0000] {log.py:232} WARNING - 2025-05-15 19:40:13,905 - INFO: SUMMARY: 0 manga updated, 0 manga added
[2025-05-15T19:40:13.905+0000] {update_sequential.py:120} INFO - SUMMARY: 0 manga updated, 0 manga added
[2025-05-15T19:40:13.909+0000] {log.py:232} WARNING - 2025-05-15 19:40:13,908 - INFO: Updated 0 manga
[2025-05-15T19:40:13.908+0000] {update_manga_database_dag.py:384} INFO - Updated 0 manga
[2025-05-15T19:40:13.910+0000] {python.py:240} INFO - Done. Returned value was: {'transaction': <unusual_prefix_e9fb9e31ae047dbd2b5c59730f08a43a11cdf463_update_manga_database_dag.DatabaseTransaction object at 0x7fdc0d122780>, 'changed_manga_ids': []}
[2025-05-15T19:40:13.919+0000] {xcom.py:690} ERROR - Object of type DatabaseTransaction is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-05-15T19:40:13.922+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'unusual_prefix_e9fb9e31ae047dbd2b5c59730f08a43a11cdf463_update_manga_database_dag.DatabaseTransaction'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=key, value=value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3645, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DatabaseTransaction is not JSON serializable
[2025-05-15T19:40:13.931+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-15T19:40:13.932+0000] {logging_mixin.py:190} INFO - Task start:2025-05-15 19:40:09.345358+00:00 end:2025-05-15 19:40:13.931537+00:00 duration:4.586179
[2025-05-15T19:40:13.933+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): update_manga_db> dag:<DAG: update_manga_database> dagrun:<DagRun update_manga_database @ 2025-05-15 19:39:40.818082+00:00: manual__2025-05-15T19:39:40.818082+00:00, state:running, queued_at: 2025-05-15 19:39:40.863542+00:00. externally triggered: True>
[2025-05-15T19:40:13.934+0000] {logging_mixin.py:190} INFO - Failure caused by Object of type DatabaseTransaction is not JSON serializable
[2025-05-15T19:40:13.934+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=update_manga_database, task_id=update_manga_db, run_id=manual__2025-05-15T19:39:40.818082+00:00, execution_date=20250515T193940, start_date=20250515T194009, end_date=20250515T194013
[2025-05-15T19:40:13.963+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-15T19:40:13.964+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 20 for task update_manga_db (Object of type DatabaseTransaction is not JSON serializable; 1441)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'unusual_prefix_e9fb9e31ae047dbd2b5c59730f08a43a11cdf463_update_manga_database_dag.DatabaseTransaction'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=key, value=value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3645, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DatabaseTransaction is not JSON serializable
[2025-05-15T19:40:13.986+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-15T19:40:14.006+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-15T19:40:14.012+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
