[2025-05-15T19:37:43.977+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-15T19:37:44.007+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_manga_database.update_manga_db manual__2025-05-15T19:37:15.115454+00:00 [queued]>
[2025-05-15T19:37:44.019+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_manga_database.update_manga_db manual__2025-05-15T19:37:15.115454+00:00 [queued]>
[2025-05-15T19:37:44.019+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-15T19:37:44.034+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): update_manga_db> on 2025-05-15 19:37:15.115454+00:00
[2025-05-15T19:37:44.042+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1362) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-15T19:37:44.044+0000] {standard_task_runner.py:72} INFO - Started process 1367 to run task
[2025-05-15T19:37:44.046+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'update_manga_database', 'update_manga_db', 'manual__2025-05-15T19:37:15.115454+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/update_manga_database_dag.py', '--cfg-path', '/tmp/tmpl9x8_yz6']
[2025-05-15T19:37:44.047+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask update_manga_db
[2025-05-15T19:37:44.097+0000] {task_command.py:467} INFO - Running <TaskInstance: update_manga_database.update_manga_db manual__2025-05-15T19:37:15.115454+00:00 [running]> on host 3729034b4972
[2025-05-15T19:37:44.192+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_manga_database' AIRFLOW_CTX_TASK_ID='update_manga_db' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T19:37:15.115454+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-15T19:37:15.115454+00:00'
[2025-05-15T19:37:44.194+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-15T19:37:44.194+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-15T19:37:44.195+0000] {logging_mixin.py:190} INFO - Current task name:update_manga_db state:running start_date:2025-05-15 19:37:44.007876+00:00
[2025-05-15T19:37:44.195+0000] {logging_mixin.py:190} INFO - Dag name:update_manga_database and current dag run status:running
[2025-05-15T19:37:44.196+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-15T19:37:44.197+0000] {log.py:232} WARNING - 2025-05-15 19:37:44,197 - INFO: Starting manga data update
[2025-05-15T19:37:44.197+0000] {update_manga_database_dag.py:373} INFO - Starting manga data update
[2025-05-15T19:37:44.207+0000] {log.py:232} WARNING - 2025-05-15 19:37:44,206 - INFO: Transaction started
[2025-05-15T19:37:44.206+0000] {update_manga_database_dag.py:84} INFO - Transaction started
[2025-05-15T19:37:44.209+0000] {log.py:232} WARNING - 2025-05-15 19:37:44,209 - INFO: Checking 5 manga for updates
[2025-05-15T19:37:44.209+0000] {update_sequential.py:59} INFO - Checking 5 manga for updates
[2025-05-15T19:37:48.949+0000] {log.py:232} WARNING - 2025-05-15 19:37:48,948 - INFO: ADDED: There May Be Something There That Wasn’t There Before - Haikyuu dj (ID: e82fb7dd-edff-4593-9fff-760f018f6703)
[2025-05-15T19:37:48.948+0000] {update_sequential.py:115} INFO - ADDED: There May Be Something There That Wasn’t There Before - Haikyuu dj (ID: e82fb7dd-edff-4593-9fff-760f018f6703)
[2025-05-15T19:37:49.235+0000] {log.py:232} WARNING - 2025-05-15 19:37:49,235 - INFO: ADDED: Falling in the blue (ID: d38389ac-caeb-4a4f-8483-589ddbaf50e1)
[2025-05-15T19:37:49.235+0000] {update_sequential.py:115} INFO - ADDED: Falling in the blue (ID: d38389ac-caeb-4a4f-8483-589ddbaf50e1)
[2025-05-15T19:37:49.518+0000] {log.py:232} WARNING - 2025-05-15 19:37:49,517 - INFO: ADDED: The Maid (ID: 192ec1c9-eb9a-4771-bb79-2b9bb4adbe0e)
[2025-05-15T19:37:49.517+0000] {update_sequential.py:115} INFO - ADDED: The Maid (ID: 192ec1c9-eb9a-4771-bb79-2b9bb4adbe0e)
[2025-05-15T19:37:49.807+0000] {log.py:232} WARNING - 2025-05-15 19:37:49,804 - INFO: ADDED: The Fairy's Wish (ID: 3de96e80-6feb-450c-a169-053d40c01063)
[2025-05-15T19:37:49.804+0000] {update_sequential.py:115} INFO - ADDED: The Fairy's Wish (ID: 3de96e80-6feb-450c-a169-053d40c01063)
[2025-05-15T19:37:50.088+0000] {log.py:232} WARNING - 2025-05-15 19:37:50,088 - INFO: ADDED: I Reincarnated as a Parenting Story Extra (ID: 8dbb4f57-4e35-4fa6-88c7-2d8f8334d8db)
[2025-05-15T19:37:50.088+0000] {update_sequential.py:115} INFO - ADDED: I Reincarnated as a Parenting Story Extra (ID: 8dbb4f57-4e35-4fa6-88c7-2d8f8334d8db)
[2025-05-15T19:37:50.373+0000] {log.py:232} WARNING - 2025-05-15 19:37:50,372 - INFO: Database update complete
[2025-05-15T19:37:50.372+0000] {update_sequential.py:119} INFO - Database update complete
[2025-05-15T19:37:50.374+0000] {log.py:232} WARNING - 2025-05-15 19:37:50,374 - INFO: SUMMARY: 0 manga updated, 5 manga added
[2025-05-15T19:37:50.374+0000] {update_sequential.py:120} INFO - SUMMARY: 0 manga updated, 5 manga added
[2025-05-15T19:37:50.377+0000] {log.py:232} WARNING - 2025-05-15 19:37:50,376 - ERROR: Failed to register manga update for rollback: Boolean value of this clause is not defined
[2025-05-15T19:37:50.376+0000] {update_manga_database_dag.py:131} ERROR - Failed to register manga update for rollback: Boolean value of this clause is not defined
[2025-05-15T19:37:50.379+0000] {log.py:232} WARNING - 2025-05-15 19:37:50,378 - ERROR: Failed to update manga data: Boolean value of this clause is not defined
[2025-05-15T19:37:50.378+0000] {update_manga_database_dag.py:390} ERROR - Failed to update manga data: Boolean value of this clause is not defined
[2025-05-15T19:37:50.393+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/update_manga_database_dag.py", line 383, in update_manga_db
    transaction.register_manga_update(changed_manga_ids)
  File "/opt/airflow/dags/update_manga_database_dag.py", line 117, in register_manga_update
    if not self.manga_table:
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 591, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/update_manga_database_dag.py", line 391, in update_manga_db
    raise AirflowException(f"Manga update failed: {str(e)}")
airflow.exceptions.AirflowException: Manga update failed: Boolean value of this clause is not defined
[2025-05-15T19:37:50.408+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-15T19:37:50.409+0000] {logging_mixin.py:190} INFO - Task start:2025-05-15 19:37:44.007876+00:00 end:2025-05-15 19:37:50.408232+00:00 duration:6.400356
[2025-05-15T19:37:50.410+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): update_manga_db> dag:<DAG: update_manga_database> dagrun:<DagRun update_manga_database @ 2025-05-15 19:37:15.115454+00:00: manual__2025-05-15T19:37:15.115454+00:00, state:running, queued_at: 2025-05-15 19:37:15.142752+00:00. externally triggered: True>
[2025-05-15T19:37:50.410+0000] {logging_mixin.py:190} INFO - Failure caused by Manga update failed: Boolean value of this clause is not defined
[2025-05-15T19:37:50.411+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=update_manga_database, task_id=update_manga_db, run_id=manual__2025-05-15T19:37:15.115454+00:00, execution_date=20250515T193715, start_date=20250515T193744, end_date=20250515T193750
[2025-05-15T19:37:50.461+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-15T19:37:50.462+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task update_manga_db (Manga update failed: Boolean value of this clause is not defined; 1367)
Traceback (most recent call last):
  File "/opt/airflow/dags/update_manga_database_dag.py", line 383, in update_manga_db
    transaction.register_manga_update(changed_manga_ids)
  File "/opt/airflow/dags/update_manga_database_dag.py", line 117, in register_manga_update
    if not self.manga_table:
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 591, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/update_manga_database_dag.py", line 391, in update_manga_db
    raise AirflowException(f"Manga update failed: {str(e)}")
airflow.exceptions.AirflowException: Manga update failed: Boolean value of this clause is not defined
[2025-05-15T19:37:50.499+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-15T19:37:50.530+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-15T19:37:50.534+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
